CREATE TABLE `todo` ( 
  `id` INT AUTO_INCREMENT NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `state` TINYINT NOT NULL DEFAULT 0 ,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `dateFinish` DATE NULL,
  `user_id` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`id`)
);
CREATE TABLE `user` ( 
  `id` INT AUTO_INCREMENT NOT NULL,
  `login` VARCHAR(80) NOT NULL,
  `passwd` VARCHAR(120) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`id`),
  CONSTRAINT `ck_unique_login` UNIQUE (`login`)
);
ALTER TABLE `todo` ADD CONSTRAINT `fk_userId` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
